Refactoring passwd.
PichuChen/go-bbs pull request #14
Opened 2020-11-12 14:58 UTC by chhsiao1981

Simplifying passwd to be more robust (err-handling in for-loop).

2020-11-12 14:58 UTC, chhsiao1981 commented
This is part of PR in #8 and in #9

2020-11-12 15:13 UTC, PichuChen commented on passwd_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
不知道有沒有更好的處理法

2020-11-12 17:05 UTC, PichuChen commented on testcases.go
> +		UserID:     [PTT_IDLEN + 1]byte{83, 89, 83, 79, 80},
請用 16 進位表示

2020-11-12 17:05 UTC, PichuChen commented on testcases.go
> +		UFlag:        33557088,
請用 16 進位表示

2020-11-12 17:08 UTC, PichuChen commented on testinit.go
> +	isTest = false
這個變數的使用時機是？

2020-11-12 17:10 UTC, PichuChen commented on go.mod
> +	github.com/sirupsen/logrus v1.7.0
這個目前應該還可以先不用？

2020-11-12 17:10 UTC, PichuChen commented on go.mod
> +	golang.org/x/text v0.3.3
這個目前應該也可以先不用？

2020-11-12 17:14 UTC, PichuChen commented on passwd.go
> +	if err == io.EOF {
在這邊處理 err == io.EOF 好像有點奇怪？

2020-11-12 17:18 UTC, chhsiao1981 commented on passwd_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
這個是 gotests 弄出來的 template～

這種寫法在很多 test-framework 裡很常見～

https://github.com/cweill/GoTests-Sublime

2020-11-12 17:20 UTC, chhsiao1981 commented on passwd_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
@PichuChen 

"更好的處理法": 請先說明你覺得這種寫法哪裡會造成困擾. 才能知道"更好"的定義.

2020-11-12 17:40 UTC, PichuChen commented on fixed_bytes.go
> +func FixedBytesToString(fixedBytes []byte) string {
FixedBytes 這個名詞可能不好被理解 如果改成 CStringToString(cString []byte) string 這樣呢？

2020-11-12 17:44 UTC, PichuChen requested changes

2020-11-12 17:44 UTC, PichuChen commented on fixed_bytes.go
> +func FixedBytesToBytes(fixedBytes []byte) []byte {
FixedBytes 這個名詞可能不好被理解 如果改成 CStringToBytes(cString []byte) []byte 這樣呢？

2020-11-12 17:44 UTC, PichuChen commented on fixed_bytes_test.go
> +	str1 := [13]byte{}
這邊應該可以直接放入下面的testcase內？

2020-11-12 17:44 UTC, PichuChen commented on fixed_bytes_test.go
> +		want []byte
統一用 expected

2020-11-12 17:44 UTC, PichuChen commented on passwd_test.go
> +		want *Userec
統一用 expected

2020-11-12 17:44 UTC, PichuChen commented on passwd_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
在file_test.go 那邊是把每個欄位都寫出 if, t.Errorf 這樣，可以快速地看出是哪個欄位不對

2020-11-12 18:24 UTC, chhsiao1981 commented on testcases.go
> +		UserID:     [PTT_IDLEN + 1]byte{83, 89, 83, 79, 80},
(done)

2020-11-12 22:10 UTC, chhsiao1981 commented on testcases.go
> +		UFlag:        33557088,
(done)

2020-11-12 22:29 UTC, chhsiao1981 commented on passwd_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
(done)

2020-11-12 22:32 UTC, chhsiao1981 commented on go.mod
> +	github.com/sirupsen/logrus v1.7.0
(done)

2020-11-12 22:32 UTC, chhsiao1981 commented on go.mod
> +	golang.org/x/text v0.3.3
(done)

2020-11-12 22:32 UTC, chhsiao1981 commented on passwd.go
> +	if err == io.EOF {
(Done)

2020-11-12 22:33 UTC, chhsiao1981 commented on fixed_bytes.go
> +func FixedBytesToString(fixedBytes []byte) string {
(改成 CstrToString)

2020-11-12 22:33 UTC, chhsiao1981 commented on fixed_bytes.go
> +func FixedBytesToBytes(fixedBytes []byte) []byte {
(改成 CstrToString)

2020-11-12 22:34 UTC, chhsiao1981 commented on fixed_bytes_test.go
> +	str1 := [13]byte{}
(convention 是每個 function 有各自獨立的 test-function～)

2020-11-12 22:35 UTC, chhsiao1981 commented on fixed_bytes_test.go
> +		want []byte
(done)

2020-11-12 22:35 UTC, chhsiao1981 commented on passwd_test.go
> +		want *Userec
(done)

2020-11-12 22:37 UTC, chhsiao1981 commented on testinit.go
> +	isTest = false
(remove isTest for now.)

2020-11-13 12:06 UTC, PichuChen approved these changes

2020-11-13 12:06 UTC, merged

2020-11-13 12:07 UTC, PichuChen commented
實作 #1