Issue 16: parse favorite file
PichuChen/go-bbs pull request #27
Opened 2020-12-27 22:05 UTC by ifanchu

Added fav.go and fav_test.go to read and parse .fav file.
Tested with 01.fav and 02.fav.

2020-12-27 22:12 UTC, ifanchu commented
hmm...tests run fine on my system. Checking.

2020-12-28 04:02 UTC, PichuChen requested changes

2020-12-28 04:02 UTC, PichuChen commented on fav_test.go
> +		if diff := deep.Equal(fav, c.expected); diff != nil {
可以的話請把每個欄位一行一行比對寫出來，這樣假如測試有問題的時候可以比較快除錯，不需要另外再去檢查是不是deep這個套件有問題。

2020-12-28 04:03 UTC, PichuChen commented
新增參照 ref: #27

2020-12-28 04:35 UTC, PichuChen commented
其實我覺得是到合併標準了，還說先合併起來其他東西另外開ISSUE 起來改會比較好？

2020-12-28 07:33 UTC, ifanchu commented on fav.go
> +	FavBoardBytes  = 12 // Each FavBoardItem takes this many bytes
changed all 3 constants.

2020-12-28 07:41 UTC, ifanchu commented on fav.go
> +	LastVisit time.Time
但資料裡是有這個 LastVisit 的，留著應該還ok？

2020-12-28 07:42 UTC, ifanchu commented on fav.go
> +	BrdId     uint32
我是看`board.go`裡面用的是 `BrdName`才這樣取的，不過ok我可以改。

2020-12-28 07:44 UTC, ifanchu commented on fav.go
> +	// TODO: FavFolder.FolderId and LineId need double check. From fav.c, Item's FolderId and LineId should be
當然會過啊，其實如果uncomment掉那幾行，就是如果用fav.c裡面那個`indexFolder`, `indexLine`反而不會過，但我不知道哪個是正確的。

2020-12-28 07:47 UTC, ifanchu commented on fav.go
> +func (favt *FavItem) GetBoard() *FavBoardItem {
所以不用考慮使用這個struct的問題嗎？因為`FavItem.Item`這是一個`interface{}`，也就是caller得過來看code才會知道說這個interface必須被cast成3種struct其中一種。

如果不用考慮如何使用的話，刪掉倒也沒差。

這3個func只是為了使用上的便利。
我是傾向留著。

2020-12-28 07:48 UTC, ifanchu commented
> 其實我覺得是到合併標準了，還說先合併起來其他東西另外開ISSUE 起來改會比較好？

我改一改好了，很快。

2020-12-28 08:20 UTC, PichuChen commented on fav.go
> +func (favt *FavItem) GetBoard() *FavBoardItem {
那先留著好了，如果未來覺得需要清理程式碼的時候再做處理。

2020-12-28 08:22 UTC, PichuChen commented on fav.go
> +	// TODO: FavFolder.FolderId and LineId need double check. From fav.c, Item's FolderId and LineId should be
會不會是testing裡面的index是錯的？

2020-12-28 08:33 UTC, ifanchu commented on fav.go
> +	// TODO: FavFolder.FolderId and LineId need double check. From fav.c, Item's FolderId and LineId should be
let me check

2020-12-28 09:01 UTC, ifanchu commented on fav_test.go
> +		if diff := deep.Equal(fav, c.expected); diff != nil {
I am going to marshal the structs to `json` and compare.

2020-12-28 13:33 UTC, PichuChen approved these changes
LGTM

2020-12-28 13:34 UTC, merged